# Generated by Django 4.2.5 on 2023-10-23 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_job_comapny_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='comapny_id',
            new_name='company_id',
        ),
    ]
