# Generated by Django 4.2.5 on 2023-10-28 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_sessionmanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SessionManager',
        ),
    ]
